
import { Word } from './types';

export const WORDS_DATA: Word[] = [
  { word: 'achieve (a goal)', cleanWord: 'achieve', pronunciation: '/əˈtʃiːv/', translation: 'pasiekti (tikslą)', explanation: 'to succeed in reaching a goal' },
  { word: 'Arrogant', cleanWord: 'arrogant', pronunciation: '/ˈærəɡənt/', translation: 'arogantiškas', explanation: 'thinking that you are better and more important than other people' },
  { word: 'Assertive', cleanWord: 'assertive', pronunciation: '/əˈsɜːtɪv/', translation: 'ryžtingas, užtikrintas', explanation: 'expressing your opinion clearly and firmly so that people listen to you' },
  { word: 'at the back', cleanWord: 'at the back', pronunciation: '/ət ðə ˈbæk/', translation: 'gale', explanation: 'in the part or side that is furthest from the front' },
  { word: 'at the front', cleanWord: 'at the front', pronunciation: '/ət ðə ˈfrʌnt/', translation: 'priekyje', explanation: 'in the most forward part of something' },
  { word: 'attractive', cleanWord: 'attractive', pronunciation: '/əˈtræktɪv/', translation: 'patrauklus', explanation: '(used about a person) beautiful or nice to look at' },
  { word: 'Beautiful', cleanWord: 'beautiful', pronunciation: '/ˈbjuːtɪfl/', translation: 'gražus', explanation: 'very nice to look at' },
  { word: 'Behind', cleanWord: 'behind', pronunciation: '/bɪˈhaɪnd/', translation: 'už, už nugaros', explanation: 'in, at, or to the back of something' },
  { word: 'Bermudas', cleanWord: 'bermudas', pronunciation: '/bəˈmjuːdəz/', translation: 'Bermudų šortai', explanation: 'casual knee-length shorts' },
  { word: 'blonde-haired', cleanWord: 'blonde-haired', pronunciation: '/ˈblɒnd heəd/', translation: 'šviesiaplaukis', explanation: 'with fair or yellow hair' },
  { word: 'blue-eyed', cleanWord: 'blue-eyed', pronunciation: '/ˈbluː aɪd/', translation: 'mėlynakis', explanation: 'with blue eyes' },
  { word: 'Bob', cleanWord: 'bob', pronunciation: '/bɒb/', translation: 'trumpa šukuosena (bob)', explanation: 'a hairstyle cut short and the same length all around' },
  { word: 'broad-shouldered', cleanWord: 'broad-shouldered', pronunciation: '/ˌbrɔːd ˈʃəʊldəd/', translation: 'plačių pečių', explanation: 'having wide shoulders' },
  { word: 'Bun', cleanWord: 'bun', pronunciation: '/bʌn/', translation: 'kuodas', explanation: 'hair fastened tightly into a round shape at the back of the head' },
  { word: 'camisole top', cleanWord: 'camisole top', pronunciation: '/ˈkæmɪsəʊl tɒp/', translation: 'palaidinė su petnešėlėmis', explanation: 'a women’s loose top held up by shoulder straps' },
  { word: 'Cardigan', cleanWord: 'cardigan', pronunciation: '/ˈkɑːdɪɡən/', translation: 'megztinis (su sagomis)', explanation: 'a warm piece of clothing, often with buttons, worn on the top half of the body' },
  { word: 'cargo pants', cleanWord: 'cargo pants', pronunciation: '/ˈkɑːɡəʊ pænts/', translation: 'kelnės su kišenėmis (kargo)', explanation: 'loose trousers with pockets in various places' },
  { word: 'Chic', cleanWord: 'chic', pronunciation: '/ʃiːk/', translation: 'stilingas, elegantiškas', explanation: 'fashionable and elegant' },
  { word: 'curly (hair)', cleanWord: 'curly', pronunciation: '/ˈkɜːli/', translation: 'garbanoti (plaukai)', explanation: 'full of curls or shaped like a curl' },
  { word: 'Deadline', cleanWord: 'deadline', pronunciation: '/ˈdedlaɪn/', translation: 'terminas, galutinis laikas', explanation: 'a point in time by which something must be done' },
  { word: 'Designer', cleanWord: 'designer', pronunciation: '/dɪˈzaɪnə(r)/', translation: 'dizainerio (prekės ženklas)', explanation: 'made by a famous fashion designer' },
  { word: 'determined', cleanWord: 'determined', pronunciation: '/dɪˈtɜːmɪnd/', translation: 'ryžtingas', explanation: 'having firmly decided to do or succeed, even if difficult' },
  { word: 'dyed hair', cleanWord: 'dyed hair', pronunciation: '/daɪd heə(r)/', translation: 'dažyti plaukai', explanation: 'hair that has been coloured using a special liquid' },
  { word: 'easy-going', cleanWord: 'easy-going', pronunciation: '/ˈiːzi ˈɡəʊɪŋ/', translation: 'ramus, neįsitempęs', explanation: 'calm, relaxed and not easily upset' },
  { word: 'Elegant', cleanWord: 'elegant', pronunciation: '/ˈelɪɡənt/', translation: 'elegantiškas', explanation: 'attractive and of good style or design' },
  { word: 'emotional', cleanWord: 'emotional', pronunciation: '/ɪˈməʊʃənl/', translation: 'emocionalus', explanation: 'having strong emotions and showing them' },
  { word: 'face (a problem)', cleanWord: 'face', pronunciation: '/feɪs/', translation: 'susidurti (su problema)', explanation: 'to deal with a particular situation or difficulty' },
  { word: 'fair-haired', cleanWord: 'fair-haired', pronunciation: '/ˈfeə heəd/', translation: 'šviesiaplaukis', explanation: 'having light or blonde hair' },
  { word: 'Fleece', cleanWord: 'fleece', pronunciation: '/fliːs/', translation: 'flisinis megztinis', explanation: 'a soft warm cloth that feels like sheep’s wool; a warm top made from it' },
  { word: 'Goal', cleanWord: 'goal', pronunciation: '/ɡəʊl/', translation: 'tikslas', explanation: 'something that you hope to achieve' },
  { word: 'handsome', cleanWord: 'handsome', pronunciation: '/ˈhænsəm/', translation: 'gražus (apie vyrą)', explanation: 'attractive (often used about a man)' },
  { word: 'hoody', cleanWord: 'hoody', pronunciation: '/ˈhʊdi/', translation: 'džemperis su gobtuvu', explanation: 'a jacket or sweatshirt with a hood' },
  { word: 'impression', cleanWord: 'impression', pronunciation: '/ɪmˈpreʃn/', translation: 'Įspūdis', explanation: 'an idea, feeling, or opinion about someone/something' },
  { word: 'in front (of sth)', cleanWord: 'in front of', pronunciation: '/ɪn ˈfrʌnt/', translation: 'priešais, priekyje', explanation: 'further forward than something' },
  { word: 'in the corner', cleanWord: 'in the corner', pronunciation: '/ɪn ðə ˈkɔːnə(r)/', translation: 'kampe', explanation: 'in the part of a photo near where two edges meet' },
  { word: 'in the background', cleanWord: 'in the background', pronunciation: '/ɪn ðə ˈbækgraʊnd/', translation: 'Fone', explanation: 'in the part of a view or picture furthest away' },
  { word: 'in the foreground', cleanWord: 'in the foreground', pronunciation: '/ɪn ðə ˈfɔːɡraʊnd/', translation: 'priekyje (vaizdo)', explanation: 'the part of a view closest to the observer' },
  { word: 'in the middle', cleanWord: 'in the middle', pronunciation: '/ɪn ðə ˈmɪdl/', translation: 'viduryje', explanation: 'at about the same distance from the two sides or ends' },
  { word: 'innovative', cleanWord: 'innovative', pronunciation: '/ˈɪnəvətɪv/', translation: 'novatoriškas, kūrybiškas', explanation: 'created using new methods or ideas' },
  { word: 'joggers', cleanWord: 'joggers', pronunciation: '/ˈdʒɒɡə(r)z/', translation: 'sportinės kelnės', explanation: 'warm soft trousers for sports' },
  { word: 'lazy', cleanWord: 'lazy', pronunciation: '/ˈleɪzi/', translation: 'Tingus', explanation: 'not wanting to work' },
  { word: 'leggings', cleanWord: 'leggings', pronunciation: '/ˈleɡɪŋz/', translation: 'tamprės', explanation: 'tight trousers that fit over both legs' },
  { word: 'maxi dress', cleanWord: 'maxi dress', pronunciation: '/ˈmæksi dres/', translation: 'ilga suknelė', explanation: 'a dress covering from shoulders to ankles' },
  { word: 'mini skirt', cleanWord: 'mini skirt', pronunciation: '/ˈmɪni skɜːt/', translation: 'mini sijonas', explanation: 'a very short skirt' },
  { word: 'modest', cleanWord: 'modest', pronunciation: '/ˈmɒdɪst/', translation: 'Kuklus', explanation: 'not talking too much about your abilities' },
  { word: 'on the right/left', cleanWord: 'on the right/left', pronunciation: '/ɒn ðə raɪt, ɒn ðə left/', translation: 'dešinėje / kairėje', explanation: 'on the side that is mentioned' },
  { word: 'original', cleanWord: 'original', pronunciation: '/əˈrɪdʒənl/', translation: 'originalus', explanation: 'new and different' },
  { word: 'overcome (a problem)', cleanWord: 'overcome', pronunciation: '/ˌəʊvəˈkʌm/', translation: 'įveikti (problemą)', explanation: 'to succeed in dealing with or controlling a problem' },
  { word: 'overweight', cleanWord: 'overweight', pronunciation: '/ˌəʊvəˈweɪt/', translation: 'turintis antsvorio', explanation: 'too heavy; above normal weight' },
  { word: 'pale-skinned', cleanWord: 'pale-skinned', pronunciation: '/ˈpeɪl skɪnd/', translation: 'šviesios odos', explanation: 'having skin that is light in colour' },
  { word: 'plait', cleanWord: 'plait', pronunciation: '/plæt/', translation: 'kasa (plaukų)', explanation: 'three or more long pieces of hair crossed over each other' },
  { word: 'polo shirt', cleanWord: 'polo shirt', pronunciation: '/ˈpəʊləʊ ʃɜːt/', translation: 'polo marškinėliai', explanation: 'an informal shirt with short sleeves and a few buttons at the neck' },
  { word: 'ponytail', cleanWord: 'ponytail', pronunciation: '/ˈpəʊniteɪl/', translation: 'arklio uodega (šukuosena)', explanation: 'long hair tied at the back of the head' },
  { word: 'retro', cleanWord: 'retro', pronunciation: '/ˈretrəʊ/', translation: 'retro stiliaus', explanation: 'using styles or fashions from the recent past' },
  { word: 'second-hand', cleanWord: 'second-hand', pronunciation: '/ˌsekənd ˈhænd/', translation: 'dėvėtas, naudotas', explanation: 'already used or owned by someone else' },
  { word: 'sensitive', cleanWord: 'sensitive', pronunciation: '/ˈsensətɪv/', translation: 'Jautrus', explanation: 'understanding and aware of others’ feelings' },
  { word: 'set (a deadline)', cleanWord: 'set', pronunciation: '/set/', translation: 'nustatyti terminą', explanation: 'to choose a time by which something must be done' },
  { word: 'shaved (head)', cleanWord: 'shaved', pronunciation: '/ʃeɪvd/', translation: 'nusiskutęs (galvą)', explanation: 'having had the hair removed' },
  { word: 'short-sighted', cleanWord: 'short-sighted', pronunciation: '/ˌʃɔːt ˈsaɪtɪd/', translation: 'trumparegys', explanation: 'able to see clearly only when things are close' },
  { word: 'shy', cleanWord: 'shy', pronunciation: '/ʃaɪ/', translation: 'drovus', explanation: 'nervous or uncomfortable about meeting people' },
  { word: 'slim', cleanWord: 'slim', pronunciation: '/slɪm/', translation: 'lieknas', explanation: 'thin in an attractive way' },
  { word: 'spiky (hair)', cleanWord: 'spiky', pronunciation: '/ˈspaɪki/', translation: 'spygliuoti (plaukai)', explanation: '(about hair) sticking straight up from the head' },
  { word: 'straight (hair)', cleanWord: 'straight', pronunciation: '/streɪt/', translation: 'tiesūs (plaukai)', explanation: 'not in a curve or angle' },
  { word: '(use a) strategy', cleanWord: 'strategy', pronunciation: '/ˈstrætədʒi/', translation: 'strategija', explanation: 'a plan for achieving a particular goal' },
  { word: 'stubborn', cleanWord: 'stubborn', pronunciation: '/ˈstʌbən/', translation: 'užsispyręs', explanation: 'not wanting to do what others want; refusing to change' },
  { word: 'stunning', cleanWord: 'stunning', pronunciation: '/ˈstʌnɪŋ/', translation: 'stulbinantis, nuostabus', explanation: 'very attractive, impressive, or surprising' },
  { word: 'stylish', cleanWord: 'stylish', pronunciation: '/ˈstaɪlɪʃ/', translation: 'stilingas', explanation: 'fashionable and attractive' },
  { word: 'sun-tanned', cleanWord: 'sun-tanned', pronunciation: '/ˈsʌn tænd/', translation: 'įdegęs', explanation: '(about skin) brown from spending time in the sun' },
  { word: 'track (your) progress', cleanWord: 'track', pronunciation: '/træk ˈprəʊɡres/', translation: 'sekti pažangą', explanation: 'to follow the progress or development of something' },
  { word: 'Ugly', cleanWord: 'ugly', pronunciation: '/ˈʌɡli/', translation: 'bjaurus, negražus', explanation: 'unpleasant to look at or listen to' },
  { word: 'unattractive', cleanWord: 'unattractive', pronunciation: '/ˌʌnəˈtræktɪv/', translation: 'nepatrauklus', explanation: 'not attractive' },
  { word: 'Vest', cleanWord: 'vest', pronunciation: '/vest/', translation: 'marškinėliai be rankovių', explanation: 'a sleeveless top' },
  { word: 'vintage', cleanWord: 'vintage', pronunciation: '/ˈvɪntɪdʒ/', translation: 'senovinis, retro', explanation: 'in a style or fashion from the past' },
  { word: 'wavy (hair)', cleanWord: 'wavy', pronunciation: '/ˈweɪvi/', translation: 'banguoti plaukai', explanation: 'having curves; not straight' },
  { word: 'work towards (a goal)', cleanWord: 'work towards', pronunciation: '/wɜːk təˈwɔːdz/', translation: 'siekti (tikslo)', explanation: 'to try to reach or achieve a goal' },
];
